name = "openwebui-config-tool"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

[env.staging]
name = "openwebui-config-tool-staging"
route = "staging.openwebui-config.com/*"

[env.production]
name = "openwebui-config-tool-production"
routes = [
  { pattern = "openwebui-config.com/*", custom_domain = true },
  { pattern = "www.openwebui-config.com/*", custom_domain = true }
]

[[env.production.routes]]
pattern = "openwebui-config.com"
custom_domain = true

[build]
command = "npm run build"
cwd = "."
watch_paths = ["src/**/*"]

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.txt"]

[[rules]]
type = "Data"
globs = ["**/*.json", "**/*.wasm"]

# Serve Vite build output (SPA)
[site]
bucket = "./dist"

# Headers for security and caching
[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
