name = "openwebui-config-tool"
compatibility_date = "2025-04-01"
send_metrics = false

# Production environment
[env.production]
name = "openwebui-config-tool"
routes = [
  { pattern = "openwebui-config.com/*", zone_name = "openwebui-config.com" },
  { pattern = "www.openwebui-config.com/*", zone_name = "openwebui-config.com" },
]

# Development environment
[env.development]
name = "openwebui-config-dev"

# Serve Vite build output (SPA)
[assets]
directory = "./dist"
not_found_handling = "single-page-application"
